m-lab/travis

- README.md
- create_public_gcs_bucket.sh
- create_service_account_and_key.sh
- decrypt.sh
- deploy_app.sh
- deploy_gcs_copy.sh
- install_gcloud.sh
- support.sh
- template-travis.yml
This PR consolidates various scripts needed to support deployment automation from travis builds.
Features supported:
* creating service accounts with pre-defined roles and a key file
* a template .travis.yml file and decryption support
* deploying local files to GCS buckets
* deploying an AppEngine Flexible Environment service
Changes include:
* new script `create_public_gcs_bucket.sh`
* new script `create_service_account_and_key.sh`
* generalize `decrypt.sh`
* generalize `deploy_gcs_copy.sh`
* generalize `template-travis.yml`
* move and revise comments from `decrypt.sh` to `README.md`
* unchanged `deploy_app.sh`
* unchanged `install_gcloud.sh`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Initial version of a travis support module

- README.md
This change updates the tar command to exclude the "." directory.
Originally, "." was included in the resulting tar archive. And, this resulted in errors when unpacking the archive from travis:
```
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-x--T: Operation not permitted
tar: Exiting with failure status due to previous errors
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/2)
> Update tar command to work correctly with travis.

- README.md
- deploy_gcs_copy.sh
This change removes the special formatting of the GSPATH and uses the literal value provided by the command line. This makes the invocation of `deploy_gcs_copy.sh` easy to read in context and permits the renaming of files at their destination.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/3)
> Take the gspath parameter as a literal path.

- deploy_app.sh
This change adds support `gcloud beta app` by defining an environment variable `BETA`. For example, to deploy a Go SE service, use:
BETA=beta ./travis/deploy_app.sh .... 
If `BETA` is undefined, then the call to `gcloud` defaults to the standard `app deploy` command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/4)
> Add support for "beta" app engine deployments to support Go SE.

- README.md
- deploy_gcs_copy.sh
A short note on adding the travis repo as a submodule to a new repo.
Travis requires the read-only form of the submodule to succeed during travis integration.
Also, allow deploy_gcs_copy.sh to accept flags for `gsutil`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/6)
> Add notes for setting up the travis submodule in a repo.

- install_gcloud.sh
Now kubectl can be installed with everything else
> install_gcloud now can install components

- create_service_account_and_key.sh
This PR updates `create_service_account_and_key.sh` to respect the 30 character limit on service account names.
While this does not seem to be a limitation of the GCP web console, it does appear to be a limitation of the `gcloud` command line tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/15)
> Respect 30-character limit for service names.

- kudo.sh
This change adds a new script `kudo.sh` for loading k8s cluster credentials before running a command that uses kubectl (or related operations on the k8s api).
This is copied and renamed from the original `kubectl.sh` in the m-lab/prometheus-support repo.
Example usage:
```
kudo.sh mlab-sandbox prometheus-federation ./script-that-uses-kubectl.sh
```
> Add kudo.sh to the travis repo for other projects.

- install_gcloud.sh
Significantly speeds up building containers containing multiple gcloud components.
> Install gcloud components all at once.

- setup_service_accounts_for_travis.sh
- support.sh
Deployment automation from travis requires service account credentials. For most repositories we have used an encrypted tar file of service accounts from each M-Lab project. This encrypted blob is awkward to update with a new or alternate service account key.
This change automates the creation of service accounts, the downloading credentials, and storing those credentials in travis environment variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/19)
> Add travis service account setup script.

- deploy_gcs.sh
- gcloudlib.sh
This change adds two new files to the travis repo to support using service account keys stored in travis environment variables.
`gcloudlib.sh` can contain common operations for gcloud or gsutil commands.
`deploy_gcs.sh` uses functions from gcloudlib.sh to activate base64 encoded service account keys to upload uncached files to GCS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/20)
> Add gcloudlib and support deploy_gcs using environment SA keys

- install_gcloud.sh
Currently, Travis builds of NDT are immensely verbose, in part due to installing the google-cloud-sdk, which does a verbose untarring of a very large tar file. This should make our Travis logs easier to read, and may even [solve a build bug with the latest Travis Trusty images where hugely copious stdout causes errors](https://github.com/travis-ci/travis-ci/issues/4704).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/21)
> Redirects stdout of google-cloud-sdk install process to /dev/null

- deploy_gcs.sh
- gcloudlib.sh
This change modifies gcloudlib.sh to expect service account keys to be available from the environment and that the key content is raw json (not encoded with base64 or in any other way obfuscated).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/22)
> Load service account key from environment

- deploy_gcs.sh
- gcloudlib.sh
This change allows `deploy_gcs.sh` to accept multiple source arguments just like `gsutil cp` can.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/23)
> Accept multiple source files

- activate_service_account.sh
- setup_service_accounts_for_travis.sh
This change removes the base64 encoding step when creating new service account keys.
Repos that create keys like this should activate the key during a travis build using either the helper script `activate_service_account.sh <KEY NAME>` or use the gcloudlib.sh function `activate_service_account` from more elaborate deployment scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/24)
> Do not base64 encode service accounts

- deploy_app.sh
I'd like to have app engine deployments have access to the travis env vars associated with their deployment.  Does this seem like a suitable way to do that?
Started by doing it in ETL, but that requires lots of repeated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/25)
> add sed to substitute travis vars

- build_rpm.sh
This PR moves the build_rpm.sh script from ndt-support repo so that various *-support repos can use it  here (by including this repo as a submodule). There was a TODO in the build_rpm.sh file itself to do this, so I'm just taking care of the TODO. A PR to the ndt-support repo will immediately follow this one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/31)
> Adds the build_rpm.sh script to this repo

- deploy_rpm.sh
This PR add the script deploy_rpm.sh from the ndt-support repo to make it more widely available to other *-support repos. This was a TODO in that file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/32)
> Moves the deploy_rpm.sh script from the ndt-support repo

- deploy_app.sh
- deploy_app_legacy_keyfile.sh
This change modifies `deploy_app.sh` to support the new (preferable) raw key form of activating service account keys.
As well, this copies the legacy keyfile support where needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/34)
> Support raw keys by name in deploy_app.sh

- kubectl.sh
This change adds a simple wrapper script that gets k8s cluster credentials before running a command, such as a deploy script.
The original version was in m-lab/prometheus-support to support deploying prometheus configuration to various clusters.
This version modifies the script to support travis keynames instead of credential files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/36)
> Add kubectl.sh to travis repo

- README.md
- setup_service_accounts_for_travis.sh
This change updates the instructions for setting up service account keys in a new project.
As well, this change makes the creation of mlab-testing service account keys optional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/37)
> Update README instructions and make mlab-testing keys optional

- download_service_account_key.sh
This PR adds a script to support local development with service account credentials.
Setting up service account credentials locally can ease development with travis.
`download_service_account_key.sh` downloads a new key for an existing service account and shows the commands to run to enable the credentials in the same way that travis does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/39)
> Add support script for downloading a service account key

- deploy_app.sh
This introduces an environment variable to determine what tags will be substituted (using envsubst) in the app.yaml file.
This simplifies introduction of environment variables for new appengine deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/43)
> allow arbitrary SUBST_TAGS

- schedule_appengine_job.sh
To replace the `cron.yaml` configuration now required by multiple repositories, this change adds a script to create jobs in the new Google Cloud Scheduler service that should perform the same purpose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/44)
> Add simple script to create an AppEngine Cloud Scheduler job

- kubectl.sh
We are now creating clusters with --region, which means that location is a region, not a zone.  This updates the script to distinguish between these and do the right thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/travis/46)
> Update to use zone or region as appropriate
